# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://avildes.github.io/caderno-do-concurseiro" # the base hostname & protocol for your site

github_username:  avildes

# Build settings
markdown: kramdown

paginate: 4

author: Your name

gems: [jekyll-paginate]
